### ISSUE TITLE
Dataset 구축

### ISSUE THREAD

**Issue by ycw1879** [kookmin-sw/capstone-2020-11#1]
더 좋은 Dataset을 찾아야합니다.

**Comment by ShineySun** [comment]
데이터셋의 경우, 7호관 내에서 직접 영상을 찍으며 만들어야 될 것 같음.

그러나 현재 7호관 건물 출입이 금지된 상태라 Yolo 환경 구축에 더 힘을 쏟는 편이 나을듯.

**Comment by ycw1879** [comment]
추가로 카메라의 Exposure, White_Balance, Gain 등을 조절하여 화질개선 및 맞춤형 환경으로 변환하여 구축중입니다.
