### ISSUE TITLE
Wheel Alignment 조절 및 직진 보정 알고리즘 개발

### ISSUE THREAD

**Issue by ShineySun** [kookmin-sw/capstone-2020-11#2]
로봇에 직진 조향값을 주었을때, 미세하게 기울어서 진행하는 사실을 확인. 

Encoder 정보 및 Odometry 정보를 bag 파일로 저장하고, 분석을 할 필요가 있어보임.

하드웨어 설계상 문제로 판단 될 시, 바닥면의 타일 부분을 차선으로 생성하여 직진 보정 알고리즘 개발 필요

**Comment by ycw1879** [comment]
Wheel Alignment 조절하기에 있어 영상처리로 직진 보정 알고리즘을 시도 했습니다. 결과가 좋습니다.

**Comment by ycw1879** [comment]
Sliding Window를 사용하여 직진보정 완료 하였습니다
